env: InvertedPendulum-v4
random_seed: 7
update_period: 250
network:
  num_layers: 2
  num_hidden: 32
  activation: ReLU
target_network:
  rho: 0.9  # rho for polyak averaging
optimizer:
  lr: 0.0001
replay_buffer:
  max_size: 5000
batch_size: 64
discount_gamma: 0.99